from typing import Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        description="The message sent by the customer.",
        examples=["My order hasn't arrived."],
    )
    conversation_id: Optional[str] = Field(
        None,
        description="Unique identifier for the chat session.",
        examples=["123"],
    )


class ChatResponse(BaseModel):
    response: str = Field(
        ...,
        description="The response message generated by SupportPilot.",
        examples=[
            "I understand your concern. Could you please provide your order number so I can help you further?"
        ],
    )
    conversation_id: Optional[str] = Field(
        None,
        description="Unique identifier for the chat session.",
        examples=["123"],
    )

